spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:h2:mem:inventory-db
  h2:
    console:
      enabled: true
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
server:
  port: 8082
